# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OceanFetchLength
                                 A QGIS plugin
 Create ocean wave fetch lines and output it's length
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-01-06
        copyright            : (C) 2025 by nedisy
        email                : nedi.sawgo.yogya@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OceanFetchLength class from file OceanFetchLength.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ocean_fetch_length import OceanFetchLength
    return OceanFetchLength(iface)
